packages:
  - "apps/*"
  - "packages/*"

catalog:
  # Runtime
  next: 15.5.18
  react: ^19.2.0
  react-dom: ^19.2.0
  "@vercel/analytics": ^2.0.1
  "@vercel/speed-insights": ^2.0.0
  next-themes: ^0.4.6
  tailwind-merge: ^3.5.0
  motion: ^12.23.24
  class-variance-authority: ^0.7.1
  "@tabler/icons-react": ^3.35.0

  # Dev
  typescript: 5.9.2
  eslint: ^9.38.0
  "@types/node": ^25.9.3
  "@types/react": 19.2.0
  "@types/react-dom": 19.2.0
  tailwindcss: ^4.2.4
  "@tailwindcss/postcss": ^4.2.4
  postcss: ^8.5.15
  tailwindcss-animate: ^1.0.7
  react-scan: ^0.5.3
